Build shared library on cygwin
cpptest/cpptest pull request #20
Opened 2024-02-18 02:56 UTC by fd00

```
$ uname -srvmpio
CYGWIN_NT-10.0-22000 3.5.0-1.x86_64 2024-02-01 11:02 UTC x86_64 unknown unknown Cygwin
$ cd /usr/src
$ git clone https://github.com/cpptest/cpptest.git
$ cd cpptest
$ ./autogen.sh
$ ./configure --enable-shared --disable-static
$ make V=1
: 
/bin/sh ../libtool  --tag=CXX   --mode=link g++ -std=c++11   -g -O2 -version-info 1:8:0  -o libcpptest.la -rpath /usr/local/lib collectoroutput.lo compileroutput.lo htmloutput.lo missing.lo source.lo suite.lo textoutput.lo time.lo utils.lo
libtool:   error: can't build x86_64-pc-cygwin shared library unless -no-undefined is specified
```

Due to Windows platform limitations, this option is required when building shared libraries.
Without this option, only static libraries can be built.

https://www.gnu.org/software/libtool/manual/html_node/LT_005fINIT.html
> This option should be used if the package has been ported to build clean dlls on win32 platforms. Usually this means that any library data items are exported with __declspec(dllexport) and imported with __declspec(dllimport). If this option is not used, libtool will assume that the package libraries are not dll clean and will build only static libraries on win32 hosts.
> 
> Provision must be made to pass -no-undefined to libtool in link mode from the package Makefile. Naturally, if you pass -no-undefined, you must ensure that all the library symbols really are defined at link time!

2024-02-18 15:11 UTC, hartwork requested changes
Hi @fd00 thanks for the pull request! Could you rebase this against latest `master` where #21 is merged so that we're sure this doesn't break the build on Linux, in practice?

2024-02-19 10:57 UTC, fd00 commented
I have checked CI pass after rebase.
- https://github.com/fd00/cpptest/actions/runs/7951834280/job/21709082022

However, `git describe` in `check-abi.sh` failed because I had only cloned the master branch.
I manually tagged `2.0.0` to resolve this.
- https://github.com/fd00/cpptest/actions/runs/7951831938/job/21705718108
- https://github.com/fd00/cpptest/releases/tag/2.0.0

2024-02-21 14:56 UTC, hartwork commented
> I have checked CI pass after rebase.
> 
> * https://github.com/fd00/cpptest/actions/runs/7951834280/job/21709082022

@fd00 cool, thanks!

> However, `git describe` in `check-abi.sh` failed because I had only cloned the master branch. I manually tagged `2.0.0` to resolve this.
> 
> * https://github.com/fd00/cpptest/actions/runs/7951831938/job/21705718108
> 
> * https://github.com/fd00/cpptest/releases/tag/2.0.0

Thanks for the report! I have a new pull request #22 to address the issue. Could you delete the 2.0.0 tag again and see if it makes the CI work in your fork, as expected?

I'll merge this one here now, thanks for your contribution! :+1:

2024-02-21 14:56 UTC, merged

2024-02-23 00:15 UTC, fd00 commented
> Could you delete the 2.0.0 tag again and see if it makes the CI work in your fork, as expected?

LGTM
https://github.com/fd00/cpptest/actions/runs/8012707116

2024-02-23 19:40 UTC, hartwork commented
@fd00 cool, thanks for testing! :+1: